export { ACTION, AFTER, DATA_CATEGORY, DEMAND_STATUS, LEGAL_BASE_TYPE, MOTIVE, POLICY_TYPE, PROCESSING_CATEGORY, PROVENANCE, PURPOSE, REQUEST_STATUS, TARGET, TARGET_DIRECTION, TRANSPARENCY_ACTION } from './priv-terms.js';
//# sourceMappingURL=index.js.map
