commitsOnly: true
types:
  - build
  - ci
  - docs
  - feat
  - fix
  - perf
  - refactor
  - release
  - test
  - chore
scopes:
  - '@blindnet/bridge'
  - '@blindnet/privacy-portal'
  - '@blindnet/core'
  - '@blindnet/core-ui'
  - '@blindnet/consent-checkbox'
  - '@blindnet/configuration'
  - '@blindnet-demos/modules'
  - '@blindnet-demos/dpo'
allowMergeCommits: false
allowRevertCommits: true
targetUrl: 'https://github.com/blindnet-io/privacy-components-web/blob/main/CONTRIBUTING.md#-commit-message-guidelines'
