/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DataSubjectPayload } from './DataSubjectPayload';
import {
  DataSubjectPayloadFromJSON,
  DataSubjectPayloadFromJSONTyped,
  DataSubjectPayloadToJSON,
} from './DataSubjectPayload';
import type { PrivacyRequestDemand } from './PrivacyRequestDemand';
import {
  PrivacyRequestDemandFromJSON,
  PrivacyRequestDemandFromJSONTyped,
  PrivacyRequestDemandToJSON,
} from './PrivacyRequestDemand';

/**
 *
 * @export
 * @interface CreatePrivacyRequestPayload
 */
export interface CreatePrivacyRequestPayload {
  /**
   *
   * @type {string}
   * @memberof CreatePrivacyRequestPayload
   */
  target?: CreatePrivacyRequestPayloadTargetEnum;
  /**
   *
   * @type {string}
   * @memberof CreatePrivacyRequestPayload
   */
  email?: string;
  /**
   *
   * @type {Array<PrivacyRequestDemand>}
   * @memberof CreatePrivacyRequestPayload
   */
  demands?: Array<PrivacyRequestDemand>;
  /**
   *
   * @type {Array<DataSubjectPayload>}
   * @memberof CreatePrivacyRequestPayload
   */
  data_subject?: Array<DataSubjectPayload>;
}

/**
 * @export
 * @enum {string}
 */
export enum CreatePrivacyRequestPayloadTargetEnum {
  Star = '*',
  Organization = 'ORGANIZATION',
  System = 'SYSTEM',
  Partners = 'PARTNERS',
  PartnersDownward = 'PARTNERS.DOWNWARD',
  PartnersUpward = 'PARTNERS.UPWARD',
}

/**
 * Check if a given object implements the CreatePrivacyRequestPayload interface.
 */
export function instanceOfCreatePrivacyRequestPayload(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function CreatePrivacyRequestPayloadFromJSON(
  json: any
): CreatePrivacyRequestPayload {
  return CreatePrivacyRequestPayloadFromJSONTyped(json, false);
}

export function CreatePrivacyRequestPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreatePrivacyRequestPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    target: !exists(json, 'target') ? undefined : json['target'],
    email: !exists(json, 'email') ? undefined : json['email'],
    demands: !exists(json, 'demands')
      ? undefined
      : (json['demands'] as Array<any>).map(PrivacyRequestDemandFromJSON),
    data_subject: !exists(json, 'data_subject')
      ? undefined
      : (json['data_subject'] as Array<any>).map(DataSubjectPayloadFromJSON),
  };
}

export function CreatePrivacyRequestPayloadToJSON(
  value?: CreatePrivacyRequestPayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    target: value.target,
    email: value.email,
    demands:
      value.demands === undefined
        ? undefined
        : (value.demands as Array<any>).map(PrivacyRequestDemandToJSON),
    data_subject:
      value.data_subject === undefined
        ? undefined
        : (value.data_subject as Array<any>).map(DataSubjectPayloadToJSON),
  };
}
