/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * origin of the data category
 * @export
 * @interface CreateProvenancePayload
 */
export interface CreateProvenancePayload {
  /**
   * data category for which the provenance is created
   * @type {string}
   * @memberof CreateProvenancePayload
   */
  data_category: string;
  /**
   * provenance type
   * @type {string}
   * @memberof CreateProvenancePayload
   */
  provenance: CreateProvenancePayloadProvenanceEnum;
  /**
   * id of the system data category originated from. null for own system
   * @type {string}
   * @memberof CreateProvenancePayload
   */
  system?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateProvenancePayloadProvenanceEnum {
  Star = '*',
  Derived = 'DERIVED',
  Transferred = 'TRANSFERRED',
  User = 'USER',
  UserDataSubject = 'USER.DATA-SUBJECT',
}

/**
 * Check if a given object implements the CreateProvenancePayload interface.
 */
export function instanceOfCreateProvenancePayload(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'data_category' in value;
  isInstance = isInstance && 'provenance' in value;

  return isInstance;
}

export function CreateProvenancePayloadFromJSON(
  json: any
): CreateProvenancePayload {
  return CreateProvenancePayloadFromJSONTyped(json, false);
}

export function CreateProvenancePayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateProvenancePayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data_category: json['data_category'],
    provenance: json['provenance'],
    system: !exists(json, 'system') ? undefined : json['system'],
  };
}

export function CreateProvenancePayloadToJSON(
  value?: CreateProvenancePayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data_category: value.data_category,
    provenance: value.provenance,
    system: value.system,
  };
}
