/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DataSubjectPayload
 */
export interface DataSubjectPayload {
  /**
   *
   * @type {string}
   * @memberof DataSubjectPayload
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof DataSubjectPayload
   */
  schema?: string;
}

/**
 * Check if a given object implements the DataSubjectPayload interface.
 */
export function instanceOfDataSubjectPayload(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;

  return isInstance;
}

export function DataSubjectPayloadFromJSON(json: any): DataSubjectPayload {
  return DataSubjectPayloadFromJSONTyped(json, false);
}

export function DataSubjectPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DataSubjectPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    schema: !exists(json, 'schema') ? undefined : json['schema'],
  };
}

export function DataSubjectPayloadToJSON(
  value?: DataSubjectPayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    schema: value.schema,
  };
}
