/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DateRangeRestriction
 */
export interface DateRangeRestriction {
  /**
   *
   * @type {Date}
   * @memberof DateRangeRestriction
   */
  from?: Date;
  /**
   *
   * @type {Date}
   * @memberof DateRangeRestriction
   */
  to?: Date;
}

/**
 * Check if a given object implements the DateRangeRestriction interface.
 */
export function instanceOfDateRangeRestriction(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function DateRangeRestrictionFromJSON(json: any): DateRangeRestriction {
  return DateRangeRestrictionFromJSONTyped(json, false);
}

export function DateRangeRestrictionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DateRangeRestriction {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    from: !exists(json, 'from') ? undefined : new Date(json['from']),
    to: !exists(json, 'to') ? undefined : new Date(json['to']),
  };
}

export function DateRangeRestrictionToJSON(
  value?: DateRangeRestriction | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    from: value.from === undefined ? undefined : value.from.toISOString(),
    to: value.to === undefined ? undefined : value.to.toISOString(),
  };
}
