/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum DemandResolution {
  Auto = 'auto',
  Manual = 'manual',
}

export function DemandResolutionFromJSON(json: any): DemandResolution {
  return DemandResolutionFromJSONTyped(json, false);
}

export function DemandResolutionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DemandResolution {
  return json as DemandResolution;
}

export function DemandResolutionToJSON(value?: DemandResolution | null): any {
  return value as any;
}
