/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DenyDemandPayload
 */
export interface DenyDemandPayload {
  /**
   *
   * @type {string}
   * @memberof DenyDemandPayload
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof DenyDemandPayload
   */
  motive: DenyDemandPayloadMotiveEnum;
  /**
   *
   * @type {string}
   * @memberof DenyDemandPayload
   */
  msg?: string;
  /**
   *
   * @type {string}
   * @memberof DenyDemandPayload
   */
  lang?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum DenyDemandPayloadMotiveEnum {
  IdentityUnconfirmed = 'IDENTITY-UNCONFIRMED',
  LanguageUnsupported = 'LANGUAGE-UNSUPPORTED',
  ValidReasons = 'VALID-REASONS',
  Impossible = 'IMPOSSIBLE',
  NoSuchData = 'NO-SUCH-DATA',
  RequestUnsupported = 'REQUEST-UNSUPPORTED',
  UserUnknown = 'USER-UNKNOWN',
  OtherMotive = 'OTHER-MOTIVE',
}

/**
 * Check if a given object implements the DenyDemandPayload interface.
 */
export function instanceOfDenyDemandPayload(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'motive' in value;

  return isInstance;
}

export function DenyDemandPayloadFromJSON(json: any): DenyDemandPayload {
  return DenyDemandPayloadFromJSONTyped(json, false);
}

export function DenyDemandPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DenyDemandPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    motive: json['motive'],
    msg: !exists(json, 'msg') ? undefined : json['msg'],
    lang: !exists(json, 'lang') ? undefined : json['lang'],
  };
}

export function DenyDemandPayloadToJSON(value?: DenyDemandPayload | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    motive: value.motive,
    msg: value.msg,
    lang: value.lang,
  };
}
