/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GivenConsentsPayload
 */
export interface GivenConsentsPayload {
  /**
   *
   * @type {string}
   * @memberof GivenConsentsPayload
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof GivenConsentsPayload
   */
  name?: string;
  /**
   *
   * @type {Date}
   * @memberof GivenConsentsPayload
   */
  date: Date;
}

/**
 * Check if a given object implements the GivenConsentsPayload interface.
 */
export function instanceOfGivenConsentsPayload(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'date' in value;

  return isInstance;
}

export function GivenConsentsPayloadFromJSON(json: any): GivenConsentsPayload {
  return GivenConsentsPayloadFromJSONTyped(json, false);
}

export function GivenConsentsPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GivenConsentsPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    name: !exists(json, 'name') ? undefined : json['name'],
    date: new Date(json['date']),
  };
}

export function GivenConsentsPayloadToJSON(
  value?: GivenConsentsPayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    date: value.date.toISOString(),
  };
}
