/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PrItem
 */
export interface PrItem {
  /**
   *
   * @type {string}
   * @memberof PrItem
   */
  id: string;
  /**
   *
   * @type {Date}
   * @memberof PrItem
   */
  date: Date;
  /**
   *
   * @type {number}
   * @memberof PrItem
   */
  demands: number;
  /**
   *
   * @type {string}
   * @memberof PrItem
   */
  status: PrItemStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum PrItemStatusEnum {
  InProcessing = 'IN_PROCESSING',
  PartiallyCompleted = 'PARTIALLY_COMPLETED',
  Completed = 'COMPLETED',
  Canceled = 'CANCELED',
}

/**
 * Check if a given object implements the PrItem interface.
 */
export function instanceOfPrItem(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'date' in value;
  isInstance = isInstance && 'demands' in value;
  isInstance = isInstance && 'status' in value;

  return isInstance;
}

export function PrItemFromJSON(json: any): PrItem {
  return PrItemFromJSONTyped(json, false);
}

export function PrItemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PrItem {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    date: new Date(json['date']),
    demands: json['demands'],
    status: json['status'],
  };
}

export function PrItemToJSON(value?: PrItem | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    date: value.date.toISOString(),
    demands: value.demands,
    status: value.status,
  };
}
