/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PrivacyScopeDimensionsPayload
 */
export interface PrivacyScopeDimensionsPayload {
  /**
   *
   * @type {Array<string>}
   * @memberof PrivacyScopeDimensionsPayload
   */
  data_categories?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof PrivacyScopeDimensionsPayload
   */
  processing_categories?: Array<PrivacyScopeDimensionsPayloadProcessingCategoriesEnum>;
  /**
   *
   * @type {Array<string>}
   * @memberof PrivacyScopeDimensionsPayload
   */
  purposes?: Array<PrivacyScopeDimensionsPayloadPurposesEnum>;
}

/**
 * @export
 * @enum {string}
 */
export enum PrivacyScopeDimensionsPayloadProcessingCategoriesEnum {
  Star = '*',
  Anonymization = 'ANONYMIZATION',
  AutomatedInference = 'AUTOMATED-INFERENCE',
  AutomatedDecisionMaking = 'AUTOMATED-DECISION-MAKING',
  Collection = 'COLLECTION',
  Generating = 'GENERATING',
  Publishing = 'PUBLISHING',
  Storing = 'STORING',
  Sharing = 'SHARING',
  Using = 'USING',
  OtherProcessing = 'OTHER-PROCESSING',
}
/**
 * @export
 * @enum {string}
 */
export enum PrivacyScopeDimensionsPayloadPurposesEnum {
  Star = '*',
  Advertising = 'ADVERTISING',
  Compliance = 'COMPLIANCE',
  Employment = 'EMPLOYMENT',
  Justice = 'JUSTICE',
  Marketing = 'MARKETING',
  Medical = 'MEDICAL',
  Personalization = 'PERSONALIZATION',
  PublicInterests = 'PUBLIC-INTERESTS',
  Research = 'RESEARCH',
  Sale = 'SALE',
  Security = 'SECURITY',
  Services = 'SERVICES',
  ServicesAdditionalServices = 'SERVICES.ADDITIONAL-SERVICES',
  ServicesBasicService = 'SERVICES.BASIC-SERVICE',
  SocialProtection = 'SOCIAL-PROTECTION',
  Tracking = 'TRACKING',
  VitalInterests = 'VITAL-INTERESTS',
  OtherPurpose = 'OTHER-PURPOSE',
}

/**
 * Check if a given object implements the PrivacyScopeDimensionsPayload interface.
 */
export function instanceOfPrivacyScopeDimensionsPayload(
  value: object
): boolean {
  let isInstance = true;

  return isInstance;
}

export function PrivacyScopeDimensionsPayloadFromJSON(
  json: any
): PrivacyScopeDimensionsPayload {
  return PrivacyScopeDimensionsPayloadFromJSONTyped(json, false);
}

export function PrivacyScopeDimensionsPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PrivacyScopeDimensionsPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data_categories: !exists(json, 'data_categories')
      ? undefined
      : json['data_categories'],
    processing_categories: !exists(json, 'processing_categories')
      ? undefined
      : json['processing_categories'],
    purposes: !exists(json, 'purposes') ? undefined : json['purposes'],
  };
}

export function PrivacyScopeDimensionsPayloadToJSON(
  value?: PrivacyScopeDimensionsPayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data_categories: value.data_categories,
    processing_categories: value.processing_categories,
    purposes: value.purposes,
  };
}
