/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Provenance
 */
export interface Provenance {
  /**
   *
   * @type {string}
   * @memberof Provenance
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Provenance
   */
  provenance: ProvenanceProvenanceEnum;
  /**
   *
   * @type {string}
   * @memberof Provenance
   */
  system?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum ProvenanceProvenanceEnum {
  Star = '*',
  Derived = 'DERIVED',
  Transferred = 'TRANSFERRED',
  User = 'USER',
  UserDataSubject = 'USER.DATA-SUBJECT',
}

/**
 * Check if a given object implements the Provenance interface.
 */
export function instanceOfProvenance(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'provenance' in value;

  return isInstance;
}

export function ProvenanceFromJSON(json: any): Provenance {
  return ProvenanceFromJSONTyped(json, false);
}

export function ProvenanceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Provenance {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    provenance: json['provenance'],
    system: !exists(json, 'system') ? undefined : json['system'],
  };
}

export function ProvenanceToJSON(value?: Provenance | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    provenance: value.provenance,
    system: value.system,
  };
}
