/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RegulationResponsePayload
 */
export interface RegulationResponsePayload {
  /**
   *
   * @type {string}
   * @memberof RegulationResponsePayload
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof RegulationResponsePayload
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof RegulationResponsePayload
   */
  description?: string;
}

/**
 * Check if a given object implements the RegulationResponsePayload interface.
 */
export function instanceOfRegulationResponsePayload(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'name' in value;

  return isInstance;
}

export function RegulationResponsePayloadFromJSON(
  json: any
): RegulationResponsePayload {
  return RegulationResponsePayloadFromJSONTyped(json, false);
}

export function RegulationResponsePayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RegulationResponsePayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    description: !exists(json, 'description') ? undefined : json['description'],
  };
}

export function RegulationResponsePayloadToJSON(
  value?: RegulationResponsePayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    description: value.description,
  };
}
