/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ConsentRestriction } from './ConsentRestriction';
import {
  ConsentRestrictionFromJSON,
  ConsentRestrictionFromJSONTyped,
  ConsentRestrictionToJSON,
} from './ConsentRestriction';
import type { DataReferenceRestriction } from './DataReferenceRestriction';
import {
  DataReferenceRestrictionFromJSON,
  DataReferenceRestrictionFromJSONTyped,
  DataReferenceRestrictionToJSON,
} from './DataReferenceRestriction';
import type { DateRangeRestriction } from './DateRangeRestriction';
import {
  DateRangeRestrictionFromJSON,
  DateRangeRestrictionFromJSONTyped,
  DateRangeRestrictionToJSON,
} from './DateRangeRestriction';
import type { PrivacyScopeRestriction } from './PrivacyScopeRestriction';
import {
  PrivacyScopeRestrictionFromJSON,
  PrivacyScopeRestrictionFromJSONTyped,
  PrivacyScopeRestrictionToJSON,
} from './PrivacyScopeRestriction';
import type { ProvenanceRestriction } from './ProvenanceRestriction';
import {
  ProvenanceRestrictionFromJSON,
  ProvenanceRestrictionFromJSONTyped,
  ProvenanceRestrictionToJSON,
} from './ProvenanceRestriction';

/**
 *
 * @export
 * @interface Restrictions
 */
export interface Restrictions {
  /**
   *
   * @type {Array<PrivacyScopeRestriction>}
   * @memberof Restrictions
   */
  privacy_scope?: Array<PrivacyScopeRestriction>;
  /**
   *
   * @type {ConsentRestriction}
   * @memberof Restrictions
   */
  consent?: ConsentRestriction;
  /**
   *
   * @type {DateRangeRestriction}
   * @memberof Restrictions
   */
  date_range?: DateRangeRestriction;
  /**
   *
   * @type {ProvenanceRestriction}
   * @memberof Restrictions
   */
  provenance?: ProvenanceRestriction;
  /**
   *
   * @type {DataReferenceRestriction}
   * @memberof Restrictions
   */
  data_reference?: DataReferenceRestriction;
}

/**
 * Check if a given object implements the Restrictions interface.
 */
export function instanceOfRestrictions(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function RestrictionsFromJSON(json: any): Restrictions {
  return RestrictionsFromJSONTyped(json, false);
}

export function RestrictionsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Restrictions {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    privacy_scope: !exists(json, 'privacy_scope')
      ? undefined
      : (json['privacy_scope'] as Array<any>).map(
          PrivacyScopeRestrictionFromJSON
        ),
    consent: !exists(json, 'consent')
      ? undefined
      : ConsentRestrictionFromJSON(json['consent']),
    date_range: !exists(json, 'date_range')
      ? undefined
      : DateRangeRestrictionFromJSON(json['date_range']),
    provenance: !exists(json, 'provenance')
      ? undefined
      : ProvenanceRestrictionFromJSON(json['provenance']),
    data_reference: !exists(json, 'data_reference')
      ? undefined
      : DataReferenceRestrictionFromJSON(json['data_reference']),
  };
}

export function RestrictionsToJSON(value?: Restrictions | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    privacy_scope:
      value.privacy_scope === undefined
        ? undefined
        : (value.privacy_scope as Array<any>).map(
            PrivacyScopeRestrictionToJSON
          ),
    consent: ConsentRestrictionToJSON(value.consent),
    date_range: DateRangeRestrictionToJSON(value.date_range),
    provenance: ProvenanceRestrictionToJSON(value.provenance),
    data_reference: DataReferenceRestrictionToJSON(value.data_reference),
  };
}
