/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ScopePayload
 */
export interface ScopePayload {
  /**
   *
   * @type {string}
   * @memberof ScopePayload
   */
  dc: string;
  /**
   *
   * @type {string}
   * @memberof ScopePayload
   */
  pc: ScopePayloadPcEnum;
  /**
   *
   * @type {string}
   * @memberof ScopePayload
   */
  pp: ScopePayloadPpEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ScopePayloadPcEnum {
  Star = '*',
  Anonymization = 'ANONYMIZATION',
  AutomatedInference = 'AUTOMATED-INFERENCE',
  AutomatedDecisionMaking = 'AUTOMATED-DECISION-MAKING',
  Collection = 'COLLECTION',
  Generating = 'GENERATING',
  Publishing = 'PUBLISHING',
  Storing = 'STORING',
  Sharing = 'SHARING',
  Using = 'USING',
  OtherProcessing = 'OTHER-PROCESSING',
}
/**
 * @export
 * @enum {string}
 */
export enum ScopePayloadPpEnum {
  Star = '*',
  Advertising = 'ADVERTISING',
  Compliance = 'COMPLIANCE',
  Employment = 'EMPLOYMENT',
  Justice = 'JUSTICE',
  Marketing = 'MARKETING',
  Medical = 'MEDICAL',
  Personalization = 'PERSONALIZATION',
  PublicInterests = 'PUBLIC-INTERESTS',
  Research = 'RESEARCH',
  Sale = 'SALE',
  Security = 'SECURITY',
  Services = 'SERVICES',
  ServicesAdditionalServices = 'SERVICES.ADDITIONAL-SERVICES',
  ServicesBasicService = 'SERVICES.BASIC-SERVICE',
  SocialProtection = 'SOCIAL-PROTECTION',
  Tracking = 'TRACKING',
  VitalInterests = 'VITAL-INTERESTS',
  OtherPurpose = 'OTHER-PURPOSE',
}

/**
 * Check if a given object implements the ScopePayload interface.
 */
export function instanceOfScopePayload(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'dc' in value;
  isInstance = isInstance && 'pc' in value;
  isInstance = isInstance && 'pp' in value;

  return isInstance;
}

export function ScopePayloadFromJSON(json: any): ScopePayload {
  return ScopePayloadFromJSONTyped(json, false);
}

export function ScopePayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ScopePayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    dc: json['dc'],
    pc: json['pc'],
    pp: json['pp'],
  };
}

export function ScopePayloadToJSON(value?: ScopePayload | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    dc: value.dc,
    pc: value.pc,
    pp: value.pp,
  };
}
