/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DataSubjectPayload } from './DataSubjectPayload';
import {
  DataSubjectPayloadFromJSON,
  DataSubjectPayloadFromJSONTyped,
  DataSubjectPayloadToJSON,
} from './DataSubjectPayload';

/**
 *
 * @export
 * @interface StartLegitimateInterestPayload
 */
export interface StartLegitimateInterestPayload {
  /**
   *
   * @type {DataSubjectPayload}
   * @memberof StartLegitimateInterestPayload
   */
  dataSubject: DataSubjectPayload;
  /**
   *
   * @type {string}
   * @memberof StartLegitimateInterestPayload
   */
  legitimateInterestId: string;
  /**
   *
   * @type {Date}
   * @memberof StartLegitimateInterestPayload
   */
  date: Date;
}

/**
 * Check if a given object implements the StartLegitimateInterestPayload interface.
 */
export function instanceOfStartLegitimateInterestPayload(
  value: object
): boolean {
  let isInstance = true;
  isInstance = isInstance && 'dataSubject' in value;
  isInstance = isInstance && 'legitimateInterestId' in value;
  isInstance = isInstance && 'date' in value;

  return isInstance;
}

export function StartLegitimateInterestPayloadFromJSON(
  json: any
): StartLegitimateInterestPayload {
  return StartLegitimateInterestPayloadFromJSONTyped(json, false);
}

export function StartLegitimateInterestPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): StartLegitimateInterestPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    dataSubject: DataSubjectPayloadFromJSON(json['dataSubject']),
    legitimateInterestId: json['legitimateInterestId'],
    date: new Date(json['date']),
  };
}

export function StartLegitimateInterestPayloadToJSON(
  value?: StartLegitimateInterestPayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    dataSubject: DataSubjectPayloadToJSON(value.dataSubject),
    legitimateInterestId: value.legitimateInterestId,
    date: value.date.toISOString(),
  };
}
