/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AddRegulationsPayload
 */
export interface AddRegulationsPayload {
  /**
   *
   * @type {Array<string>}
   * @memberof AddRegulationsPayload
   */
  regulationIds?: Array<string>;
}

/**
 * Check if a given object implements the AddRegulationsPayload interface.
 */
export function instanceOfAddRegulationsPayload(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function AddRegulationsPayloadFromJSON(
  json: any
): AddRegulationsPayload {
  return AddRegulationsPayloadFromJSONTyped(json, false);
}

export function AddRegulationsPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AddRegulationsPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    regulationIds: !exists(json, 'regulation_ids')
      ? undefined
      : json['regulation_ids'],
  };
}

export function AddRegulationsPayloadToJSON(
  value?: AddRegulationsPayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    regulation_ids: value.regulationIds,
  };
}
