/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ApproveDemandPayload
 */
export interface ApproveDemandPayload {
  /**
   *
   * @type {string}
   * @memberof ApproveDemandPayload
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ApproveDemandPayload
   */
  msg?: string;
  /**
   *
   * @type {string}
   * @memberof ApproveDemandPayload
   */
  lang?: string;
}

/**
 * Check if a given object implements the ApproveDemandPayload interface.
 */
export function instanceOfApproveDemandPayload(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;

  return isInstance;
}

export function ApproveDemandPayloadFromJSON(json: any): ApproveDemandPayload {
  return ApproveDemandPayloadFromJSONTyped(json, false);
}

export function ApproveDemandPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApproveDemandPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    msg: !exists(json, 'msg') ? undefined : json['msg'],
    lang: !exists(json, 'lang') ? undefined : json['lang'],
  };
}

export function ApproveDemandPayloadToJSON(
  value?: ApproveDemandPayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    msg: value.msg,
    lang: value.lang,
  };
}
