/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CancelDemandPayload
 */
export interface CancelDemandPayload {
  /**
   *
   * @type {string}
   * @memberof CancelDemandPayload
   */
  demandId: string;
}

/**
 * Check if a given object implements the CancelDemandPayload interface.
 */
export function instanceOfCancelDemandPayload(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'demandId' in value;

  return isInstance;
}

export function CancelDemandPayloadFromJSON(json: any): CancelDemandPayload {
  return CancelDemandPayloadFromJSONTyped(json, false);
}

export function CancelDemandPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CancelDemandPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    demandId: json['demand_id'],
  };
}

export function CancelDemandPayloadToJSON(
  value?: CancelDemandPayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    demand_id: value.demandId,
  };
}
