/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ConsentRestriction
 */
export interface ConsentRestriction {
  /**
   *
   * @type {string}
   * @memberof ConsentRestriction
   */
  id: string;
}

/**
 * Check if a given object implements the ConsentRestriction interface.
 */
export function instanceOfConsentRestriction(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;

  return isInstance;
}

export function ConsentRestrictionFromJSON(json: any): ConsentRestriction {
  return ConsentRestrictionFromJSONTyped(json, false);
}

export function ConsentRestrictionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ConsentRestriction {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
  };
}

export function ConsentRestrictionToJSON(
  value?: ConsentRestriction | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
  };
}
