/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * keep CONTACT for no longer than 30 days after a service defined by a legal base ends
 * @export
 * @interface CreateRetentionPolicyPayload
 */
export interface CreateRetentionPolicyPayload {
  /**
   * data category for which the policy is created
   * @type {string}
   * @memberof CreateRetentionPolicyPayload
   */
  dataCategory: string;
  /**
   * retention policy
   * @type {string}
   * @memberof CreateRetentionPolicyPayload
   */
  policy: CreateRetentionPolicyPayloadPolicyEnum;
  /**
   * duration in JSON Schema duration format
   * @type {string}
   * @memberof CreateRetentionPolicyPayload
   */
  duration: string;
  /**
   * event type to which the retention duration is relative to
   * @type {string}
   * @memberof CreateRetentionPolicyPayload
   */
  after: CreateRetentionPolicyPayloadAfterEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateRetentionPolicyPayloadPolicyEnum {
  LongerThan = 'NO-LONGER-THAN',
  LessThan = 'NO-LESS-THAN',
}
/**
 * @export
 * @enum {string}
 */
export enum CreateRetentionPolicyPayloadAfterEnum {
  CaptureDate = 'CAPTURE-DATE',
  RelationshipStart = 'RELATIONSHIP-START',
  RelationshipEnd = 'RELATIONSHIP-END',
  ServiceStart = 'SERVICE-START',
  ServiceEnd = 'SERVICE-END',
}

/**
 * Check if a given object implements the CreateRetentionPolicyPayload interface.
 */
export function instanceOfCreateRetentionPolicyPayload(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'dataCategory' in value;
  isInstance = isInstance && 'policy' in value;
  isInstance = isInstance && 'duration' in value;
  isInstance = isInstance && 'after' in value;

  return isInstance;
}

export function CreateRetentionPolicyPayloadFromJSON(
  json: any
): CreateRetentionPolicyPayload {
  return CreateRetentionPolicyPayloadFromJSONTyped(json, false);
}

export function CreateRetentionPolicyPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateRetentionPolicyPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    dataCategory: json['data_category'],
    policy: json['policy'],
    duration: json['duration'],
    after: json['after'],
  };
}

export function CreateRetentionPolicyPayloadToJSON(
  value?: CreateRetentionPolicyPayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data_category: value.dataCategory,
    policy: value.policy,
    duration: value.duration,
    after: value.after,
  };
}
