/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateSelectorPayload
 */
export interface CreateSelectorPayload {
  /**
   * selector name
   * @type {string}
   * @memberof CreateSelectorPayload
   */
  name: string;
  /**
   * selector is the subcategory of this data category
   * @type {string}
   * @memberof CreateSelectorPayload
   */
  dataCategory: string;
}

/**
 * Check if a given object implements the CreateSelectorPayload interface.
 */
export function instanceOfCreateSelectorPayload(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'name' in value;
  isInstance = isInstance && 'dataCategory' in value;

  return isInstance;
}

export function CreateSelectorPayloadFromJSON(
  json: any
): CreateSelectorPayload {
  return CreateSelectorPayloadFromJSONTyped(json, false);
}

export function CreateSelectorPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateSelectorPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    dataCategory: json['data_category'],
  };
}

export function CreateSelectorPayloadToJSON(
  value?: CreateSelectorPayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    data_category: value.dataCategory,
  };
}
