/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Provenance } from './Provenance';
import {
  ProvenanceFromJSON,
  ProvenanceFromJSONTyped,
  ProvenanceToJSON,
} from './Provenance';
import type { RetentionPolicy } from './RetentionPolicy';
import {
  RetentionPolicyFromJSON,
  RetentionPolicyFromJSONTyped,
  RetentionPolicyToJSON,
} from './RetentionPolicy';

/**
 *
 * @export
 * @interface DataCategoryResponsePayload
 */
export interface DataCategoryResponsePayload {
  /**
   *
   * @type {string}
   * @memberof DataCategoryResponsePayload
   */
  dataCategory: string;
  /**
   *
   * @type {Array<Provenance>}
   * @memberof DataCategoryResponsePayload
   */
  provenances?: Array<Provenance>;
  /**
   *
   * @type {Array<RetentionPolicy>}
   * @memberof DataCategoryResponsePayload
   */
  retentionPolicies?: Array<RetentionPolicy>;
}

/**
 * Check if a given object implements the DataCategoryResponsePayload interface.
 */
export function instanceOfDataCategoryResponsePayload(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'dataCategory' in value;

  return isInstance;
}

export function DataCategoryResponsePayloadFromJSON(
  json: any
): DataCategoryResponsePayload {
  return DataCategoryResponsePayloadFromJSONTyped(json, false);
}

export function DataCategoryResponsePayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DataCategoryResponsePayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    dataCategory: json['data_category'],
    provenances: !exists(json, 'provenances')
      ? undefined
      : (json['provenances'] as Array<any>).map(ProvenanceFromJSON),
    retentionPolicies: !exists(json, 'retention_policies')
      ? undefined
      : (json['retention_policies'] as Array<any>).map(RetentionPolicyFromJSON),
  };
}

export function DataCategoryResponsePayloadToJSON(
  value?: DataCategoryResponsePayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data_category: value.dataCategory,
    provenances:
      value.provenances === undefined
        ? undefined
        : (value.provenances as Array<any>).map(ProvenanceToJSON),
    retention_policies:
      value.retentionPolicies === undefined
        ? undefined
        : (value.retentionPolicies as Array<any>).map(RetentionPolicyToJSON),
  };
}
