/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DataReferenceRestriction
 */
export interface DataReferenceRestriction {
  /**
   *
   * @type {Array<string>}
   * @memberof DataReferenceRestriction
   */
  ref?: Array<string>;
}

/**
 * Check if a given object implements the DataReferenceRestriction interface.
 */
export function instanceOfDataReferenceRestriction(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function DataReferenceRestrictionFromJSON(
  json: any
): DataReferenceRestriction {
  return DataReferenceRestrictionFromJSONTyped(json, false);
}

export function DataReferenceRestrictionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DataReferenceRestriction {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ref: !exists(json, 'ref') ? undefined : json['ref'],
  };
}

export function DataReferenceRestrictionToJSON(
  value?: DataReferenceRestriction | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ref: value.ref,
  };
}
