/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DataCallbackPayload
 */
export interface DataCallbackPayload {
  /**
   *
   * @type {string}
   * @memberof DataCallbackPayload
   */
  requestId: string;
  /**
   *
   * @type {boolean}
   * @memberof DataCallbackPayload
   */
  accepted: boolean;
  /**
   *
   * @type {string}
   * @memberof DataCallbackPayload
   */
  dataUrl?: string;
}

/**
 * Check if a given object implements the DataCallbackPayload interface.
 */
export function instanceOfDataCallbackPayload(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'requestId' in value;
  isInstance = isInstance && 'accepted' in value;

  return isInstance;
}

export function DataCallbackPayloadFromJSON(json: any): DataCallbackPayload {
  return DataCallbackPayloadFromJSONTyped(json, false);
}

export function DataCallbackPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DataCallbackPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    requestId: json['request_id'],
    accepted: json['accepted'],
    dataUrl: !exists(json, 'data_url') ? undefined : json['data_url'],
  };
}

export function DataCallbackPayloadToJSON(
  value?: DataCallbackPayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    request_id: value.requestId,
    accepted: value.accepted,
    data_url: value.dataUrl,
  };
}
