/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DataSubjectPayload } from './DataSubjectPayload';
import {
  DataSubjectPayloadFromJSON,
  DataSubjectPayloadFromJSONTyped,
  DataSubjectPayloadToJSON,
} from './DataSubjectPayload';

/**
 *
 * @export
 * @interface EndContractPayload
 */
export interface EndContractPayload {
  /**
   *
   * @type {DataSubjectPayload}
   * @memberof EndContractPayload
   */
  dataSubject: DataSubjectPayload;
  /**
   *
   * @type {string}
   * @memberof EndContractPayload
   */
  contractId: string;
  /**
   *
   * @type {Date}
   * @memberof EndContractPayload
   */
  date: Date;
}

/**
 * Check if a given object implements the EndContractPayload interface.
 */
export function instanceOfEndContractPayload(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'dataSubject' in value;
  isInstance = isInstance && 'contractId' in value;
  isInstance = isInstance && 'date' in value;

  return isInstance;
}

export function EndContractPayloadFromJSON(json: any): EndContractPayload {
  return EndContractPayloadFromJSONTyped(json, false);
}

export function EndContractPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EndContractPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    dataSubject: DataSubjectPayloadFromJSON(json['dataSubject']),
    contractId: json['contractId'],
    date: new Date(json['date']),
  };
}

export function EndContractPayloadToJSON(
  value?: EndContractPayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    dataSubject: DataSubjectPayloadToJSON(value.dataSubject),
    contractId: value.contractId,
    date: value.date.toISOString(),
  };
}
