/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GeneralInformation
 */
export interface GeneralInformation {
  /**
   * countries where data servers are located (including those of the processors who are processing data on your behalf
   * @type {Array<string>}
   * @memberof GeneralInformation
   */
  countries?: Array<string>;
  /**
   * name and contact details of your Organization and its representative
   * @type {string}
   * @memberof GeneralInformation
   */
  organization: string;
  /**
   * identity and contact of a Data Protection Officer - if you are using blindnet devkit Privacy Request Builder, include the URL where you are hosting the interface
   * @type {string}
   * @memberof GeneralInformation
   */
  dpo: string;
  /**
   * list of unique descriptive identifiers of Data Consumer Categories
   * @type {Array<string>}
   * @memberof GeneralInformation
   */
  dataConsumerCategories?: Array<string>;
  /**
   * public URL where your Privacy Policy can be consulted
   * @type {string}
   * @memberof GeneralInformation
   */
  privacyPolicyLink?: string;
  /**
   * general description of the technical and organizational security measures referred to in Article 32 of GDPR
   * @type {string}
   * @memberof GeneralInformation
   */
  dataSecurityInfo?: string;
}

/**
 * Check if a given object implements the GeneralInformation interface.
 */
export function instanceOfGeneralInformation(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'organization' in value;
  isInstance = isInstance && 'dpo' in value;

  return isInstance;
}

export function GeneralInformationFromJSON(json: any): GeneralInformation {
  return GeneralInformationFromJSONTyped(json, false);
}

export function GeneralInformationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GeneralInformation {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    countries: !exists(json, 'countries') ? undefined : json['countries'],
    organization: json['organization'],
    dpo: json['dpo'],
    dataConsumerCategories: !exists(json, 'data_consumer_categories')
      ? undefined
      : json['data_consumer_categories'],
    privacyPolicyLink: !exists(json, 'privacy_policy_link')
      ? undefined
      : json['privacy_policy_link'],
    dataSecurityInfo: !exists(json, 'data_security_info')
      ? undefined
      : json['data_security_info'],
  };
}

export function GeneralInformationToJSON(
  value?: GeneralInformation | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    countries: value.countries,
    organization: value.organization,
    dpo: value.dpo,
    data_consumer_categories: value.dataConsumerCategories,
    privacy_policy_link: value.privacyPolicyLink,
    data_security_info: value.dataSecurityInfo,
  };
}
