/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PrivacyScopeTriple } from './PrivacyScopeTriple';
import {
  PrivacyScopeTripleFromJSON,
  PrivacyScopeTripleFromJSONTyped,
  PrivacyScopeTripleToJSON,
} from './PrivacyScopeTriple';

/**
 *
 * @export
 * @interface PrivacyScope
 */
export interface PrivacyScope {
  /**
   *
   * @type {Array<PrivacyScopeTriple>}
   * @memberof PrivacyScope
   */
  triples?: Array<PrivacyScopeTriple>;
}

/**
 * Check if a given object implements the PrivacyScope interface.
 */
export function instanceOfPrivacyScope(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function PrivacyScopeFromJSON(json: any): PrivacyScope {
  return PrivacyScopeFromJSONTyped(json, false);
}

export function PrivacyScopeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PrivacyScope {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    triples: !exists(json, 'triples')
      ? undefined
      : (json['triples'] as Array<any>).map(PrivacyScopeTripleFromJSON),
  };
}

export function PrivacyScopeToJSON(value?: PrivacyScope | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    triples:
      value.triples === undefined
        ? undefined
        : (value.triples as Array<any>).map(PrivacyScopeTripleToJSON),
  };
}
