/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PrivacyScopeTriple
 */
export interface PrivacyScopeTriple {
  /**
   *
   * @type {string}
   * @memberof PrivacyScopeTriple
   */
  dataCategory: string;
  /**
   *
   * @type {string}
   * @memberof PrivacyScopeTriple
   */
  processingCategory: PrivacyScopeTripleProcessingCategoryEnum;
  /**
   *
   * @type {string}
   * @memberof PrivacyScopeTriple
   */
  purpose: PrivacyScopeTriplePurposeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum PrivacyScopeTripleProcessingCategoryEnum {
  Star = '*',
  Anonymization = 'ANONYMIZATION',
  AutomatedInference = 'AUTOMATED-INFERENCE',
  AutomatedDecisionMaking = 'AUTOMATED-DECISION-MAKING',
  Collection = 'COLLECTION',
  Generating = 'GENERATING',
  Publishing = 'PUBLISHING',
  Storing = 'STORING',
  Sharing = 'SHARING',
  Using = 'USING',
  OtherProcessing = 'OTHER-PROCESSING',
}
/**
 * @export
 * @enum {string}
 */
export enum PrivacyScopeTriplePurposeEnum {
  Star = '*',
  Advertising = 'ADVERTISING',
  Compliance = 'COMPLIANCE',
  Employment = 'EMPLOYMENT',
  Justice = 'JUSTICE',
  Marketing = 'MARKETING',
  Medical = 'MEDICAL',
  Personalization = 'PERSONALIZATION',
  PublicInterests = 'PUBLIC-INTERESTS',
  Research = 'RESEARCH',
  Sale = 'SALE',
  Security = 'SECURITY',
  Services = 'SERVICES',
  ServicesAdditionalServices = 'SERVICES.ADDITIONAL-SERVICES',
  ServicesBasicService = 'SERVICES.BASIC-SERVICE',
  SocialProtection = 'SOCIAL-PROTECTION',
  Tracking = 'TRACKING',
  VitalInterests = 'VITAL-INTERESTS',
  OtherPurpose = 'OTHER-PURPOSE',
}

/**
 * Check if a given object implements the PrivacyScopeTriple interface.
 */
export function instanceOfPrivacyScopeTriple(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'dataCategory' in value;
  isInstance = isInstance && 'processingCategory' in value;
  isInstance = isInstance && 'purpose' in value;

  return isInstance;
}

export function PrivacyScopeTripleFromJSON(json: any): PrivacyScopeTriple {
  return PrivacyScopeTripleFromJSONTyped(json, false);
}

export function PrivacyScopeTripleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PrivacyScopeTriple {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    dataCategory: json['data_category'],
    processingCategory: json['processing_category'],
    purpose: json['purpose'],
  };
}

export function PrivacyScopeTripleToJSON(
  value?: PrivacyScopeTriple | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data_category: value.dataCategory,
    processing_category: value.processingCategory,
    purpose: value.purpose,
  };
}
