/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PrivacyRequestCreatedPayload
 */
export interface PrivacyRequestCreatedPayload {
  /**
   *
   * @type {string}
   * @memberof PrivacyRequestCreatedPayload
   */
  requestId: string;
}

/**
 * Check if a given object implements the PrivacyRequestCreatedPayload interface.
 */
export function instanceOfPrivacyRequestCreatedPayload(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'requestId' in value;

  return isInstance;
}

export function PrivacyRequestCreatedPayloadFromJSON(
  json: any
): PrivacyRequestCreatedPayload {
  return PrivacyRequestCreatedPayloadFromJSONTyped(json, false);
}

export function PrivacyRequestCreatedPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PrivacyRequestCreatedPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    requestId: json['request_id'],
  };
}

export function PrivacyRequestCreatedPayloadToJSON(
  value?: PrivacyRequestCreatedPayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    request_id: value.requestId,
  };
}
