/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PrItem } from './PrItem';
import { PrItemFromJSON, PrItemFromJSONTyped, PrItemToJSON } from './PrItem';

/**
 *
 * @export
 * @interface RequestHistoryPayload
 */
export interface RequestHistoryPayload {
  /**
   *
   * @type {Array<PrItem>}
   * @memberof RequestHistoryPayload
   */
  history?: Array<PrItem>;
}

/**
 * Check if a given object implements the RequestHistoryPayload interface.
 */
export function instanceOfRequestHistoryPayload(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function RequestHistoryPayloadFromJSON(
  json: any
): RequestHistoryPayload {
  return RequestHistoryPayloadFromJSONTyped(json, false);
}

export function RequestHistoryPayloadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RequestHistoryPayload {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    history: !exists(json, 'history')
      ? undefined
      : (json['history'] as Array<any>).map(PrItemFromJSON),
  };
}

export function RequestHistoryPayloadToJSON(
  value?: RequestHistoryPayload | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    history:
      value.history === undefined
        ? undefined
        : (value.history as Array<any>).map(PrItemToJSON),
  };
}
