/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { DataCallbackPayload } from '../models';
import {
  DataCallbackPayloadFromJSON,
  DataCallbackPayloadToJSON,
} from '../models';

export interface PostV0CallbackCallbackidRequest {
  callbackId: string;
  dataCallbackPayload: DataCallbackPayload;
}

/**
 *
 */
export class CallbacksApi extends runtime.BaseAPI {
  /**
   * Link to access data in the storage created
   */
  async postV0CallbackCallbackidRaw(
    requestParameters: PostV0CallbackCallbackidRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<void>> {
    if (
      requestParameters.callbackId === null ||
      requestParameters.callbackId === undefined
    ) {
      throw new runtime.RequiredError(
        'callbackId',
        'Required parameter requestParameters.callbackId was null or undefined when calling postV0CallbackCallbackid.'
      );
    }

    if (
      requestParameters.dataCallbackPayload === null ||
      requestParameters.dataCallbackPayload === undefined
    ) {
      throw new runtime.RequiredError(
        'dataCallbackPayload',
        'Required parameter requestParameters.dataCallbackPayload was null or undefined when calling postV0CallbackCallbackid.'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/v0/callback/{callbackId}`.replace(
          `{${'callbackId'}}`,
          encodeURIComponent(String(requestParameters.callbackId))
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: DataCallbackPayloadToJSON(requestParameters.dataCallbackPayload),
      },
      initOverrides
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Link to access data in the storage created
   */
  async postV0CallbackCallbackid(
    requestParameters: PostV0CallbackCallbackidRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<void> {
    await this.postV0CallbackCallbackidRaw(requestParameters, initOverrides);
  }
}
