/* tslint:disable */
/* eslint-disable */
/**
 * Privacy computation engine
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { GivenConsentsPayload } from '../models';
import {
  GivenConsentsPayloadFromJSON,
  GivenConsentsPayloadToJSON,
} from '../models';

export interface GetV0UserConsentsRequest {
  authorization: string;
}

/**
 *
 */
export class UserInfoApi extends runtime.BaseAPI {
  /**
   * Get a list of consents user has given
   */
  async getV0UserConsentsRaw(
    requestParameters: GetV0UserConsentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<GivenConsentsPayload>>> {
    if (
      requestParameters.authorization === null ||
      requestParameters.authorization === undefined
    ) {
      throw new runtime.RequiredError(
        'authorization',
        'Required parameter requestParameters.authorization was null or undefined when calling getV0UserConsents.'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      requestParameters.authorization !== undefined &&
      requestParameters.authorization !== null
    ) {
      headerParameters['Authorization'] = String(
        requestParameters.authorization
      );
    }

    const response = await this.request(
      {
        path: `/v0/user/consents`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, jsonValue =>
      jsonValue.map(GivenConsentsPayloadFromJSON)
    );
  }

  /**
   * Get a list of consents user has given
   */
  async getV0UserConsents(
    requestParameters: GetV0UserConsentsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<GivenConsentsPayload>> {
    const response = await this.getV0UserConsentsRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
