var ACTION;
(function (ACTION) {
    ACTION["ACCESS"] = "ACCESS";
    ACTION["DELETE"] = "DELETE";
    ACTION["MODIFY"] = "MODIFY";
    ACTION["OBJECT"] = "OBJECT";
    ACTION["PORTABILITY"] = "PORTABILITY";
    ACTION["RESTRICT"] = "RESTRICT";
    ACTION["REVOKE"] = "REVOKE-CONSENT";
    ACTION["TRANSPARENCY"] = "TRANSPARENCY";
    ACTION["TRANSPARENCY.DATA.CATEGORIES"] = "TRANSPARENCY.DATA-CATEGORIES";
    ACTION["TRANSPARENCY.DPO"] = "TRANSPARENCY.DPO";
    ACTION["TRANSPARENCY.KNOWN"] = "TRANSPARENCY.KNOWN";
    ACTION["TRANSPARENCY.LEGAL.BASES"] = "TRANSPARENCY.LEGAL-BASES";
    ACTION["TRANSPARENCY.ORGANIZATION"] = "TRANSPARENCY.ORGANIZATION";
    ACTION["TRANSPARENCY.POLICY"] = "TRANSPARENCY.POLICY";
    ACTION["TRANSPARENCY.PROCESSING.CATEGORIES"] = "TRANSPARENCY.PROCESSING-CATEGORIES";
    ACTION["TRANSPARENCY.PROVENANCE"] = "TRANSPARENCY.PROVENANCE";
    ACTION["TRANSPARENCY.PURPOSE"] = "TRANSPARENCY.PURPOSE";
    ACTION["TRANSPARENCY.RETENTION"] = "TRANSPARENCY.RETENTION";
    ACTION["TRANSPARENCY.WHERE"] = "TRANSPARENCY.WHERE";
    ACTION["TRANSPARENCY.WHO"] = "TRANSPARENCY.WHO";
    ACTION["OTHER.DEMAND"] = "OTHER-DEMAND";
})(ACTION || (ACTION = {}));
var TRANSPARENCY_ACTION;
(function (TRANSPARENCY_ACTION) {
    TRANSPARENCY_ACTION["TRANSPARENCY_DATA_CATEGORIES"] = "TRANSPARENCY.DATA-CATEGORIES";
    TRANSPARENCY_ACTION["TRANSPARENCY_DPO"] = "TRANSPARENCY.DPO";
    TRANSPARENCY_ACTION["TRANSPARENCY_KNOWN"] = "TRANSPARENCY.KNOWN";
    TRANSPARENCY_ACTION["TRANSPARENCY_LEGAL_BASES"] = "TRANSPARENCY.LEGAL-BASES";
    TRANSPARENCY_ACTION["TRANSPARENCY_ORGANIZATION"] = "TRANSPARENCY.ORGANIZATION";
    TRANSPARENCY_ACTION["TRANSPARENCY_POLICY"] = "TRANSPARENCY.POLICY";
    TRANSPARENCY_ACTION["TRANSPARENCY_PROCESSING_CATEGORIES"] = "TRANSPARENCY.PROCESSING-CATEGORIES";
    TRANSPARENCY_ACTION["TRANSPARENCY_PROVENANCE"] = "TRANSPARENCY.PROVENANCE";
    TRANSPARENCY_ACTION["TRANSPARENCY_PURPOSE"] = "TRANSPARENCY.PURPOSE";
    TRANSPARENCY_ACTION["TRANSPARENCY_RETENTION"] = "TRANSPARENCY.RETENTION";
    TRANSPARENCY_ACTION["TRANSPARENCY_WHERE"] = "TRANSPARENCY.WHERE";
    TRANSPARENCY_ACTION["TRANSPARENCY_WHO"] = "TRANSPARENCY.WHO";
})(TRANSPARENCY_ACTION || (TRANSPARENCY_ACTION = {}));
var PROVENANCE;
(function (PROVENANCE) {
    PROVENANCE["USER"] = "USER";
    PROVENANCE["USER.DATA-SUBJECT"] = "USER.DATA-SUBJECT";
    PROVENANCE["DERIVED"] = "DERIVED";
    PROVENANCE["TRANSFERRED"] = "TRANSFERRED";
})(PROVENANCE || (PROVENANCE = {}));
var STATUS;
(function (STATUS) {
    STATUS["CANCELED"] = "CANCELED";
    STATUS["GRANTED"] = "GRANTED";
    STATUS["DENIED"] = "DENIED";
    STATUS["PARTIALLY-GRANTED"] = "PARTIALLY-GRANTED";
    STATUS["UNDER-REVIEW"] = "UNDER-REVIEW";
})(STATUS || (STATUS = {}));
var TARGET;
(function (TARGET) {
    TARGET["ORGANIZATION"] = "ORGANIZATION";
    TARGET["PARTNERS"] = "PARTNERS";
    TARGET["SYSTEM"] = "SYSTEM";
})(TARGET || (TARGET = {}));
var TARGET_DIRECTION;
(function (TARGET_DIRECTION) {
    TARGET_DIRECTION["PARTNERS.DOWNWARD"] = "PARTNERS.DOWNWARD";
    TARGET_DIRECTION["PARTNERS.UPWARD"] = "PARTNERS.UPWARD";
})(TARGET_DIRECTION || (TARGET_DIRECTION = {}));

export { ACTION, PROVENANCE, STATUS, TARGET, TARGET_DIRECTION, TRANSPARENCY_ACTION };
//# sourceMappingURL=priv-terms.js.map
